#!/bin/bash

#In anemoi v3.0 and under theres an error with checkpoints larger then 2GB
# this script fixes the checkpoint file

if [[ $1 == "" ]]; then
	echo "error! expected usage './bin/fix_ckpt </path/to/checkpoint>' exiting..."
	exit 1
fi

set -xe
checkpoint=$1
echo "Cleaning $checkpoint..."
file_name="ai-models.json"
file_zip_path=`unzip -l $checkpoint | grep $file_name | awk '{print $NF}'`
parent_dirs=`dirname $file_zip_path`
unzip -j $checkpoint $file_zip_path 2>&1 > /dev/null #copy the json out of the zip
mkdir -p $parent_dirs
mv $file_name $parent_dirs
zip -d $checkpoint $file_zip_path 2>&1 > /dev/null #delete the json inside the zip
zip $checkpoint $file_zip_path 2>&1 > /dev/null #update the path
unzip -l $checkpoint | grep $file_name #check if worked by printing the copies path within the zip
rm -rf $file_zip_path
